[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=600"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"